# Generated by Django 5.2.12 on 2026-04-02 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('cnic', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('subjects', models.CharField(blank=True, max_length=255, null=True)),
                ('managed_classes', models.CharField(blank=True, max_length=100, null=True)),
                ('current_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(blank=True, max_length=150, null=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('cnic', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('subjects', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_classes', models.CharField(blank=True, max_length=100, null=True)),
                ('current_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(blank=True, max_length=150, null=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('cnic', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('cnic', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.PositiveIntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=20, null=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.membership')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
