# Generated by Django 5.2.12 on 2026-04-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_accountactivationtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountactivationtoken',
            old_name='expired_at',
            new_name='expiration_at',
        ),
    ]
