# Generated by Django 5.2.12 on 2026-04-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_rename_expired_at_accountactivationtoken_expiration_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountactivationtoken',
            old_name='expiration_at',
            new_name='expiration_date',
        ),
    ]
