# Generated by Django 5.2.12 on 2026-05-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organizationjoinlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationjoinlink',
            name='max_users',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
