# Generated by Django 5.2.12 on 2026-05-18 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_membership_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organization.organization'),
            preserve_default=False,
        ),
    ]
