# Generated by Django 5.2.12 on 2026-05-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_membership_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='total_admins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='total_instructors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='total_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
