# Generated by Django 5.2.12 on 2026-05-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_alter_organization_total_admins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationjoinlink',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationjoinlink',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
