# Generated by Django 5.2.12 on 2026-06-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_organizationjoinlink_expired_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationjoinlink',
            name='allowed_emails',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
