"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ACTIVATION_BASE_URL = os.getenv("ACTIVATION_BASE_URL")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jdnmqr^a*1vr-3fobsb!w_!xwjtg#8+=*xj_*3jlkv7pwz!ad#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'education',
    'organization',
    'user_auth',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'user_auth.authentication.OrganizationJWTAuthentication'
    ]
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ("Bearer",),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'management_system',
        'user': 'uzair',
        'PASSWORD': 'kl55nm7qcj98pj5hg0kv74bw0vt2ny9',
        'HOST': 'localhost',
        'PORT': '5432'
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

MEDIA_URL = "/media/"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "simple": {
            "format": "%(levelname)s - %(name)s: %(message)s"
        },
    },

    "filters": {
        "ignore_django_autoreload": {
            "()": "django.utils.log.CallbackFilter",
            "callback": lambda record: "autoreload" not in record.name,
        }
    },
    "handlers": {
        "file": {
            "class": "logging.FileHandler",
            "filename": "project.log",
            "formatter": "simple",
            "filters": ["ignore_django_autoreload"],
        },
    },

    "root": {
        "handlers": ["file"],
        "level": "INFO",
    },
}



# For Uzair - Owner in Testing organization

# "tokens": {
#     "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2OTM0NTkzLCJpYXQiOjE3NzY5MzA5OTMsImp0aSI6IjljN2FhNzVlYmEyNDQ3YjY4OTQ0MmVkNmQxMGZmZGEzIiwidXNlcl9pZCI6IjM0Iiwib3JnYW5pemF0aW9uX2lkIjozLCJyb2xlIjoiT1dORVIifQ.7IyhxTIP9BVSnXv5Kej8c4w8b6Nfo8mC-xKTLHB_fyg",
#     "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NzUzNTc5MywiaWF0IjoxNzc2OTMwOTkzLCJqdGkiOiI3NGRiOTZhN2FmNGI0OGQ2YWJlZGU3MTc0NjM2NmNjYiIsInVzZXJfaWQiOiIzNCIsIm9yZ2FuaXphdGlvbl9pZCI6Mywicm9sZSI6Ik9XTkVSIn0.SEGt8Qe4ujLzIYq_STU9NiyMtxyk-YbMDN3KPRWIktM"
# }


# For asad - Instructor in Testing organization

# "tokens": {
#     "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3NTM0MjA2LCJpYXQiOjE3Nzc1MzA2MDYsImp0aSI6IjVjYjcwZjZkNDExMTQyZGFiY2Y3MmQ2ZTBiZDY4YmQ0IiwidXNlcl9pZCI6IjQ4Iiwib3JnYW5pemF0aW9uX2lkIjozLCJyb2xlIjoiSU5TVFJVQ1RPUiJ9.BsbJc_gjHszkJj2zMA2j2a8YLw1YUgsGY-MhGDa_DME",
#     "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3ODEzNTQwNiwiaWF0IjoxNzc3NTMwNjA2LCJqdGkiOiI0MjFkNjg4Njg1ZTI0MGE3OTRmMWNhNWYyZGMxZmRkNyIsInVzZXJfaWQiOiI0OCIsIm9yZ2FuaXphdGlvbl9pZCI6Mywicm9sZSI6IklOU1RSVUNUT1IifQ.jZ3YRd8Ku2C56-Gr7i4dKaTEe287SzZ2vkfVKvYjhLs"
# }


# For Ahmed - Instructor in Testing organization

# "tokens": {
#     "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3OTYzMDUwLCJpYXQiOjE3Nzc5NTk0NTAsImp0aSI6IjI5ZGQyNjQyNzQxNTRiNjdhMGU5ZWNhMGNlOTNkNzlhIiwidXNlcl9pZCI6IjM4Iiwib3JnYW5pemF0aW9uX2lkIjozLCJyb2xlIjoiSU5TVFJVQ1RPUiJ9.Div8E1kdfGRLb6hg8GstUraEa9gFTSfQqlNqhLEhesg",
#     "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3ODQ5MjUyNSwiaWF0IjoxNzc3ODg3NzI1LCJqdGkiOiIwMjk0Zjk4NTVkMzY0NWRmYTg3NWJmZDc2NDlmNWUxNCIsInVzZXJfaWQiOiIzOCIsIm9yZ2FuaXphdGlvbl9pZCI6Mywicm9sZSI6IklOU1RSVUNUT1IifQ.NXyhJnp4_C48zuRp00G5VLUy0LtRHSBhfarFCK4MIcQ"
# }


# For Rehan - Instructor in Testing organization

# "tokens": {
#     "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3OTc5OTA5LCJpYXQiOjE3Nzc5NzYzMDksImp0aSI6IjY1YTM3ZjRmOWZhYjQwYTM4NjJkMWM0MTc1MzlhZjM3IiwidXNlcl9pZCI6IjQ5Iiwib3JnYW5pemF0aW9uX2lkIjozLCJyb2xlIjoiSU5TVFJVQ1RPUiJ9.ep4I9Bs_ykL9uszy4NrWtyindIywlZQrXttGXcIlY5M",
#     "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3ODEzNTAyNSwiaWF0IjoxNzc3NTMwMjI1LCJqdGkiOiI2YTgxODE3MDM2NWM0N2I0OGVhZjZkMzk3YWY1YzIzZSIsInVzZXJfaWQiOiI0OSIsIm9yZ2FuaXphdGlvbl9pZCI6Mywicm9sZSI6IklOU1RSVUNUT1IifQ.8qFmMl_TdtZEYHAPVuxj_IvPm0QK7tuwp5tyEw_SZnM"
# }


# For idrees - Student in Testing organization --- IN USE ---

# "tokens": {
#         "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc4MTUzNDQ5LCJpYXQiOjE3NzgxNDk4NDksImp0aSI6ImIzNDVjMTYxYjk0ZTQ0ZmJhN2YyYTBmMjUxZTYzNmU4IiwidXNlcl9pZCI6IjM2Iiwib3JnYW5pemF0aW9uX2lkIjozLCJyb2xlIjoiU1RVREVOVCJ9.66prE1nN-K1Rnnzrie1j4gwJZPOkUN1F3nU3cyiQH1c",
#         "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3ODU2NTYwNywiaWF0IjoxNzc3OTYwODA3LCJqdGkiOiIyNTg3OTIyN2Q5MDY0MjE4YTExYTBiYjU0NDEwMjFjZiIsInVzZXJfaWQiOiIzNiIsIm9yZ2FuaXphdGlvbl9pZCI6Mywicm9sZSI6IlNUVURFTlQifQ.aSaVs8H-QAAuT-vcjmgjPACP3lSfhyRd_HetcaR253A"
#     }


# For faheem - Instructor in DevTesting
# "tokens": {
#     "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3OTk2NzI1LCJpYXQiOjE3Nzc5OTMxMjUsImp0aSI6ImQ2M2ZmNzQ0N2FkMDQ2YTE4NzRmM2I0MmI0OWE5OTJiIiwidXNlcl9pZCI6IjQ2Iiwib3JnYW5pemF0aW9uX2lkIjoyLCJyb2xlIjoiSU5TVFJVQ1RPUiJ9.3t5QXRfyJ1GMaEjQV7yWDYYU8Np6sHVeGwgEJ8_2LCU",
#     "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3ODU4MTY1NCwiaWF0IjoxNzc3OTc2ODU0LCJqdGkiOiIyNzRiZGJhNmJiMjk0NzExYmFkN2QwYjYwZmFkNDY2ZCIsInVzZXJfaWQiOiI0NiIsIm9yZ2FuaXphdGlvbl9pZCI6Miwicm9sZSI6IklOU1RSVUNUT1IifQ.ufCslhSPg4O6FLE58r3RzLWYym0kKsfUw-sFW3am3D0"
# }