# Generated by Django 5.2.12 on 2026-04-16 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('organization', '0002_alter_membership_organization_alter_membership_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='some-course-slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='some-lesson-slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='education.coursetype'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('organization', 'instructor', 'slug', 'type')},
        ),
    ]
