# Generated by Django 5.2.12 on 2026-04-16 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_coursetype_course_slug_lesson_slug_course_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='education.coursetype'),
            preserve_default=False,
        ),
    ]
