# Generated by Django 5.2.12 on 2026-04-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_alter_course_unique_together'),
        ('organization', '0003_alter_membership_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('organization', 'instructor', 'slug', 'type')},
        ),
    ]
