# Generated by Django 5.2.12 on 2026-04-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_remove_lesson_content_remove_lesson_video_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='LessonContent',
        ),
    ]
