# Generated by Django 5.2.12 on 2026-04-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_lesson_content_lesson_video_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='is_canceled',
            new_name='is_cancelled',
        ),
    ]
