# Generated by Django 5.2.12 on 2026-04-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_rename_is_canceled_enrollment_is_cancelled'),
        ('organization', '0003_alter_membership_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'organization'), name='unique_enrollment'),
        ),
    ]
