# Generated by Django 5.2.12 on 2026-05-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_lessonprogress'),
        ('organization', '0003_alter_membership_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'verbose_name_plural': 'lesson Progresses'},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name_plural': 'Progresses'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')]),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['course'], name='education_f_course__b25127_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['course', 'rating'], name='education_f_course__d117dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('course', 'student'), name='unique_course_feedback'),
        ),
    ]
